=== francabrera/turawet/trunk/Resources/Forms/XML/form_def.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT form (meta,sections)>
<!ATTLIST form
  xmlns CDATA #FIXED ''>

<!ELEMENT meta (id,version,name,author)>
<!ATTLIST meta
  xmlns CDATA #FIXED ''>

<!ELEMENT version (#PCDATA)>
<!ATTLIST version
  xmlns CDATA #FIXED ''>

<!ELEMENT author (user)>
<!ATTLIST author
  xmlns CDATA #FIXED ''>

<!ELEMENT sections (section)>
<!ATTLIST sections
  xmlns CDATA #FIXED ''>

<!ELEMENT user (#PCDATA)>
<!ATTLIST user
  xmlns CDATA #FIXED ''>

<!ELEMENT section (id,name,fields)>
<!ATTLIST section
  xmlns CDATA #FIXED ''>

<!ELEMENT fields (field+,group+)>
<!ATTLIST fields
  xmlns CDATA #FIXED ''>

<!ELEMENT group (id,list?,label,required?,field+,properties?)>
<!ATTLIST group
  xmlns CDATA #FIXED ''>

<!ELEMENT list EMPTY>
<!ATTLIST list
  xmlns CDATA #FIXED ''>

<!ELEMENT id EMPTY>
<!ATTLIST id
  xmlns CDATA #FIXED ''>

<!ELEMENT name (#PCDATA)>
<!ATTLIST name
  xmlns CDATA #FIXED ''>

<!ELEMENT field (id,label,type,required?,options?,properties?)>
<!ATTLIST field
  xmlns CDATA #FIXED ''>

<!ELEMENT type (#PCDATA)>
<!ATTLIST type
  xmlns CDATA #FIXED ''>

<!ELEMENT options (option)+>
<!ATTLIST options
  xmlns CDATA #FIXED ''>

<!ELEMENT properties (property)+>
<!ATTLIST properties
  xmlns CDATA #FIXED ''>

<!ELEMENT option (label,value,default?)>
<!ATTLIST option
  xmlns CDATA #FIXED ''>

<!ELEMENT property (name,value)>
<!ATTLIST property
  xmlns CDATA #FIXED ''>

<!ELEMENT default EMPTY>
<!ATTLIST default
  xmlns CDATA #FIXED ''>

<!ELEMENT required EMPTY>
<!ATTLIST required
  xmlns CDATA #FIXED ''>

<!ELEMENT label (#PCDATA)>
<!ATTLIST label
  xmlns CDATA #FIXED ''>

<!ELEMENT value (#PCDATA)>
<!ATTLIST value
  xmlns CDATA #FIXED ''>

=== francabrera/turawet/Resources/Forms/XML/formulario.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE form SYSTEM "form_def.dtd">

<form>
	<id />
	<version>1</version>
	<name>Formulario de prueba</name>
	<author>
		<user>nicopernas</user>
	</author>
	<sections>
		<section>
			<name>Primera sección</name>
			<fields>
				<field>
					<id />
					<label>Etiqueta1</label>
					<type>TEXT</type>
					<required />
					<properties>
						<property>
							<name>max_length</name>
							<value>10</value>
						</property>
					</properties>
				</field>
				<field>
					<id />
					<label>Etiqueta2</label>
					<type>TEXT</type>
					<properties>
						<property>
							<name>font</name>
							<value>Arial</value>
						</property>
					</properties>
				</field>
				<field>
					<id />
					<label>Fecha1</label>
					<type>DATE</type>
					<required />
					<properties>
						<property>
							<name>format</name>
							<value>YYYY/MM/DD</value>
						</property>
						<property>
							<name>calendar</name>
							<value>MONTH_CALENDAR</value>
						</property>
					</properties>
				</field>
				<field>
					<id />
					<label>Radio1</label>
					<type>RADIO</type>
					<required />
					<options>
						<option>
							<label>Masculino</label>
							<value>M</value>
						</option>
						<option>
							<label>Femenino</label>
							<value>F</value>
						</option>
					</options>
				</field>
				<field>
					<id />
					<label>Combo1</label>
					<type>COMBO</type>
					<options>
						<option>
							<label>Opción 1</label>
							<value>O1</value>
							<default />
						</option>
						<option>
							<label>Opción 2</label>
							<value>O2</value>
						</option>
					</options>
					<properties>
						<property>
							<name>size</name>
							<value>30</value>
						</property>
					</properties>
				</field>
				<field>
					<id />
					<label>Check1</label>
					<type>CHECKBOX</type>
					<required />
					<properties>
						<property>
							<name>widget</name>
							<value>TRISTATE</value>
						</property>
					</properties>
				</field>
				<field>
					<id />
					<label>Imágenes</label>
					<type>IMAGE_GALLERY</type>
					<required />
					<properties>
						<property>
							<name>max_photos</name>
							<value>6</value>
						</property>
					</properties>
				</field>
				<field>
					<id />
					<label>Vídeos</label>
					<type>VIDEO_GALLERY</type>
					<properties>
						<property>
							<name>max_file_size</name>
							<value>128</value>
						</property>
					</properties>
				</field>
				<field>
					<id />
					<label>Audio</label>
					<type>AUDIO_GALLERY</type>
					<properties>
						<property>
							<name>max_file_size</name>
							<value>8</value>
						</property>
					</properties>
				</field>
				<field>
					<id />
					<label>Localización</label>
					<type>LOCATION</type>
					<properties>
						<property>
							<name>type</name>
							<value>COORDINATES</value>
						</property>
					</properties>
				</field>
				<group>
					<name>GRUPO</name>
					<required />
					<field>
						<id />
						<label>Nombre</label>
						<type>TEXT</type>
					</field>
					<field>
						<id />
						<label>Apellido1</label>
						<type>TEXT</type>
					</field>
				</group>
				<group>
					<list />
					<name>LISTA</name>
					<field>
						<id />
						<label>Imágenes</label>
						<type>IMAGE_GALLERY</type>
					</field>
				</group>
			</fields>
		</section>
	</sections>
</form>

=== francabrera/turawet/trunk/BeeDroid/trunk/BeeDroid/assets/formulario.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE form SYSTEM "form_def.dtd"> -->

<form>
	<id />
	<version>1</version>
	<name>Formulario de prueba</name>
	<author>
		<user>turawet</user>
	</author>
	<sections>
		<section>
			<name>Primera secci√≥n</name>
			<fields>
				<field>
					<id>1</id>
					<label>Etiqueta1</label>
					<type>TEXT</type>
					<required />
					<properties>
						<property>
							<name>max_length</name>
							<value>10</value>
						</property>
					</properties>
				</field>
				<field>
					<id>2</id>
					<label>Fecha1</label>
					<type>DATE</type>
					<required />
					<properties>
						<property>
							<name>format</name>
							<value>YYYY/MM/DD</value>
						</property>
						<property>
							<name>calendar</name>
							<value>MONTH_CALENDAR</value>
						</property>
					</properties>
				</field>
				<field>
					<id>1</id>
					<label>Campito</label>
					<type>TEXT</type>
					<required />
					<properties>
						<property>
							<name>max_length</name>
							<value>120</value>
						</property>
					</properties>
				</field>

				<field>
					<id>2</id>
					<label>Otra fecha</label>
					<type>DATE</type>
					<required />
					<properties>
						<property>
							<name>format</name>
							<value>DD/MM/YYYY</value>
						</property>
						<property>
							<name>calendar</name>
							<value>YEAR_CALENDAR</value>
						</property>
					</properties>
				</field>

			</fields>
		</section>
	</sections>
</form>

=== francabrera/turawet/BeeDroid/trunk/BeeDroid/assets/formulario_breve_v1.xml
<?xml version='1.0' encoding='UTF-8'?><!-- <!DOCTYPE form SYSTEM 'form_def.dtd'> --><form><meta><id /><version>1</version><name>Formulario de prueba</name><author><user>turawet</user></author></meta><sections><section><id /><name>Primera secci√≥n</name><fields><field><id>1</id><label>Etiqueta1</label><type>TEXT</type><required /><properties><property><name>max_length</name><value>10</value></property></properties></field><field><id>3</id><label>Campito</label><type>TEXT</type><required /><properties><property><name>max_length</name><value>120</value></property></properties></field><field><id>1</id><label>Etiqueta1</label><type>TEXT</type><required /><properties><property><name>max_length</name><value>10</value></property></properties></field><field><id>3</id><label>Campito</label><type>TEXT</type><required /><properties><property><name>max_length</name><value>120</value></property></properties></field><field><id>1</id><label>Etiqueta1</label><type>TEXT</type><required /><properties><property><name>max_length</name><value>10</value></property></properties></field><field><id>3</id><label>Campito</label><type>TEXT</type><required /><properties><property><name>max_length</name><value>120</value></property></properties></field><field><id>1</id><label>Etiqueta1</label><type>TEXT</type><required /><properties><property><name>max_length</name><value>10</value></property></properties></field><field><id>3</id><label>Campito</label><type>TEXT</type><required /><properties><property><name>max_length</name><value>120</value></property></properties></field><field><id>1</id><label>Etiqueta1</label><type>TEXT</type><required /><properties><property><name>max_length</name><value>10</value></property></properties></field><field><id>3</id><label>Campito</label><type>TEXT</type><required /><properties><property><name>max_length</name><value>120</value></property></properties></field><field><id>1</id><label>Etiqueta1</label><type>TEXT</type><required /><properties><property><name>max_length</name><value>10</value></property></properties></field><field><id>3</id><label>Campito</label><type>TEXT</type><required /><properties><property><name>max_length</name><value>120</value></property></properties></field><field><id>1</id><label>Etiqueta1</label><type>TEXT</type><required /><properties><property><name>max_length</name><value>10</value></property></properties></field><field><id>3</id><label>Campito</label><type>TEXT</type><required /><properties><property><name>max_length</name><value>120</value></property></properties></field><field><id>1</id><label>Etiqueta1</label><type>TEXT</type><required /><properties><property><name>max_length</name><value>10</value></property></properties></field><field><id>3</id><label>Campito</label><type>TEXT</type><required /><properties><property><name>max_length</name><value>120</value></property></properties></field><field><id>1</id><label>Etiqueta1</label><type>TEXT</type><required /><properties><property><name>max_length</name><value>10</value></property></properties></field><field><id>3</id><label>Campito</label><type>TEXT</type><required /><properties><property><name>max_length</name><value>120</value></property></properties></field><field><id>1</id><label>Etiqueta1</label><type>TEXT</type><required /><properties><property><name>max_length</name><value>10</value></property></properties></field><field><id>3</id><label>Campito</label><type>TEXT</type><required /><properties><property><name>max_length</name><value>120</value></property></properties></field><field><id>1</id><label>Etiqueta1</label><type>TEXT</type><required /><properties><property><name>max_length</name><value>10</value></property></properties></field><field><id>3</id><label>Campito</label><type>TEXT</type><required /><properties><property><name>max_length</name><value>120</value></property></properties></field><field><id>1</id><label>Etiqueta1</label><type>TEXT</type><required /><properties><property><name>max_length</name><value>10</value></property></properties></field><field><id>3</id><label>Campito</label><type>TEXT</type><required /><properties><property><name>max_length</name><value>120</value></property></properties></field><field><id>1</id><label>Etiqueta1</label><type>TEXT</type><required /><properties><property><name>max_length</name><value>10</value></property></properties></field><field><id>3</id><label>Campito</label><type>TEXT</type><required /><properties><property><name>max_length</name><value>120</value></property></properties></field><field><id>1</id><label>Etiqueta1</label><type>TEXT</type><required /><properties><property><name>max_length</name><value>10</value></property></properties></field><field><id>3</id><label>Campito</label><type>TEXT</type><required /><properties><property><name>max_length</name><value>120</value></property></properties></field><field><id>1</id><label>Etiqueta1</label><type>TEXT</type><required /><properties><property><name>max_length</name><value>10</value></property></properties></field><field><id>3</id><label>Campito</label><type>TEXT</type><required /><properties><property><name>max_length</name><value>120</value></property></properties></field><field><id>1</id><label>Etiqueta1</label><type>TEXT</type><required /><properties><property><name>max_length</name><value>10</value></property></properties></field><field><id>3</id><label>Campito</label><type>TEXT</type><required /><properties><property><name>max_length</name><value>120</value></property></properties></field><field><id>1</id><label>Etiqueta1</label><type>TEXT</type><required /><properties><property><name>max_length</name><value>10</value></property></properties></field><field><id>3</id><label>Campito</label><type>TEXT</type><required /><properties><property><name>max_length</name><value>120</value></property></properties></field><field><id>1</id><label>Etiqueta1</label><type>TEXT</type><required /><properties><property><name>max_length</name><value>10</value></property></properties></field><field><id>3</id><label>Campito</label><type>TEXT</type><required /><properties><property><name>max_length</name><value>120</value></property></properties></field><field><id>1</id><label>Etiqueta1</label><type>TEXT</type><required /><properties><property><name>max_length</name><value>10</value></property></properties></field><field><id>3</id><label>Campito</label><type>TEXT</type><required /><properties><property><name>max_length</name><value>120</value></property></properties></field><field><id>1</id><label>Etiqueta1</label><type>TEXT</type><required /><properties><property><name>max_length</name><value>10</value></property></properties></field><field><id>3</id><label>Campito</label><type>TEXT</type><required /><properties><property><name>max_length</name><value>120</value></property></properties></field><field><id>1</id><label>Etiqueta1</label><type>TEXT</type><required /><properties><property><name>max_length</name><value>10</value></property></properties></field><field><id>3</id><label>Campito</label><type>TEXT</type><required /><properties><property><name>max_length</name><value>120</value></property></properties></field><field><id>1</id><label>Etiqueta1</label><type>TEXT</type><required /><properties><property><name>max_length</name><value>10</value></property></properties></field><field><id>3</id><label>Campito</label><type>TEXT</type><required /><properties><property><name>max_length</name><value>120</value></property></properties></field><field><id>1</id><label>Etiqueta1</label><type>TEXT</type><required /><properties><property><name>max_length</name><value>10</value></property></properties></field><field><id>3</id><label>Campito</label><type>TEXT</type><required /><properties><property><name>max_length</name><value>120</value></property></properties></field><field><id>1</id><label>Etiqueta1</label><type>TEXT</type><required /><properties><property><name>max_length</name><value>10</value></property></properties></field><field><id>3</id><label>Campito</label><type>TEXT</type><required /><properties><property><name>max_length</name><value>120</value></property></properties></field><field><id>1</id><label>Etiqueta1</label><type>TEXT</type><required /><properties><property><name>max_length</name><value>10</value></property></properties></field><field><id>3</id><label>Campito</label><type>TEXT</type><required /><properties><property><name>max_length</name><value>120</value></property></properties></field></fields></section></sections></form>

=== francabrera/turawet/trunk/Resources/Forms/XML/formulario.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE form SYSTEM "form_def.dtd">

<form>
	<id />
	<meta>
		<version>1</version>
		<name>Formulario de prueba</name>
		<author>
			<user>turawet</user>
		</author>
	</meta>
	<sections>
		<section>
			<id />
			<name>Primera sección</name>
			<fields>
				<field>
					<id />
					<label>Etiqueta1</label>
					<type>TEXT</type>
					<required />
					<properties>
						<property>
							<name>max_length</name>
							<value>10</value>
						</property>
					</properties>
				</field>
				<field>
					<id />
					<label>Etiqueta2</label>
					<type>TEXT</type>
					<properties>
						<property>
							<name>font</name>
							<value>Arial</value>
						</property>
					</properties>
				</field>
				<field>
					<id />
					<label>Fecha1</label>
					<type>DATE</type>
					<required />
					<properties>
						<property>
							<name>format</name>
							<value>YYYY/MM/DD</value>
						</property>
						<property>
							<name>calendar</name>
							<value>MONTH_CALENDAR</value>
						</property>
					</properties>
				</field>
				<field>
					<id />
					<label>Radio1</label>
					<type>RADIO</type>
					<required />
					<options>
						<option>
							<label>Masculino</label>
							<value>M</value>
						</option>
						<option>
							<label>Femenino</label>
							<value>F</value>
						</option>
					</options>
				</field>
				<field>
					<id />
					<label>Combo1</label>
					<type>COMBO</type>
					<options>
						<option>
							<label>Opción 1</label>
							<value>O1</value>
							<default />
						</option>
						<option>
							<label>Opción 2</label>
							<value>O2</value>
						</option>
					</options>
					<properties>
						<property>
							<name>size</name>
							<value>30</value>
						</property>
					</properties>
				</field>
				<field>
					<id />
					<label>Check1</label>
					<type>CHECKBOX</type>
					<required />
					<properties>
						<property>
							<name>widget</name>
							<value>TRISTATE</value>
						</property>
					</properties>
				</field>
				<field>
					<id />
					<label>Imagen</label>
					<type>IMAGE</type>
					<required />
				</field>
				<field>
					<id />
					<label>Vídeo</label>
					<type>VIDEO</type>
				</field>
				<field>
					<id />
					<label>Audio</label>
					<type>AUDIO</type>
				</field>
				<field>
					<id />
					<label>Localización</label>
					<type>LOCATION</type>
					<properties>
						<property>
							<name>type</name>
							<value>COORDINATES</value>
						</property>
					</properties>
				</field>
				<group>
					<id />
					<label>GRUPO</label>
					<required />
					<field>
						<id />
						<label>Nombre</label>
						<type>TEXT</type>
					</field>
					<field>
						<id />
						<label>Apellido1</label>
						<type>TEXT</type>
					</field>
				</group>
				<group>
					<id />
					<list />
					<label>Galería de imágenes</label>
					<field>
						<id />
						<label>Imágenes</label>
						<type>IMAGE_GALLERY</type>
					</field>
					<properties>
						<property>
							<name>max_photos</name>
							<value>6</value>
						</property>
						<property>
							<name>max_file_size</name>
							<value>128</value>
						</property>
					</properties>
				</group>
				<field>
					<id />
					<label>Número de ventanas</label>
					<type>NUMERIC</type>
					<required />
				</field>
			</fields>
		</section>
	</sections>
</form>

=== francabrera/turawet/BeeDroid/branches/BeeDroid_branch_2011_09_28/assets/formulario_breve_v1.xml
<?xml version='1.0' encoding='UTF-8'?><!-- <!DOCTYPE form SYSTEM 'form_def.dtd'> -->
<form>
	<meta>
		<id />
		<version>1</version>
		<name>Formulario de prueba</name>
		<author>
			<user>turawet</user>
		</author>
		<geolocalized />
	</meta>
	<sections>
		<section>
			<id />
			<name>Cuarta secci√≥n</name>
			<fields>
				<field>
					<id />
					<label>Etiqueta2</label>
					<type>TEXT</type>
					<properties>
						<property>
							<name>font</name>
							<value>Arial</value>
						</property>
					</properties>
				</field>
			</fields>
		</section>
	</sections>
</form>

=== francabrera/turawet/trunk/BeeDroid/trunk/BeeDroid/assets/formulario_breve_v1.xml
<?xml version='1.0' encoding='UTF-8'?><!-- <!DOCTYPE form SYSTEM 'form_def.dtd'> -->
<form>
	<meta>
		<id />
		<version>1</version>
		<name>Formulario de prueba</name>
		<author>
			<user>turawet</user>
		</author>
		<geolocalized />
	</meta>
	<sections>
		<section>
			<id />
			<name>Primera sección</name>

			<fields>
				<field>
					<id />
					<label>Número de ventanas</label>
					<type>NUMERIC</type>
					<required />
				</field>
				<field>
					<id />
					<label>Imagen</label>
					<type>IMAGE</type>
					<required />
				</field>
			</fields>
		</section>
		<section>
			<id />
			<name>Segunda sección</name>
			<fields>

				<field>
					<id />
					<label>Fecha1123123</label>
					<type>DATE</type>
					<required />
					<properties>
						<property>
							<name>format</name>
							<value>YYYY/MM/DD</value>
						</property>
						<property>
							<name>calendar</name>
							<value>MONTH_CALENDAR</value>
						</property>
					</properties>
				</field>
			</fields>
		</section>
		<section>
			<id />
			<name>Tercera sección</name>
			<fields>

				<field>
					<id />
					<label>Radio1</label>
					<type>RADIO</type>
					<required />
					<options>
						<option>
							<label>Rojo</label>
							<value>R</value>
						</option>
						<option>
							<label>Azul</label>
							<value>A</value>
						</option>
						<option>
							<label>Verde</label>
							<value>V</value>
						</option>
						<option>
							<label>Marrón</label>
							<value>M</value>
						</option>
						<option>
							<label>Negro</label>
							<value>N</value>
						</option>
						<option>
							<label>Rojo</label>
							<value>R</value>
						</option>
						<option>
							<label>Azul</label>
							<value>A</value>
						</option>
						<option>
							<label>Verde</label>
							<value>V</value>
						</option>
						<option>
							<label>Marrón</label>
							<value>M</value>
						</option>
						<option>
							<label>Negro</label>
							<value>N</value>
						</option>
						<option>
							<label>Rojo</label>
							<value>R</value>
						</option>
						<option>
							<label>Azul</label>
							<value>A</value>
						</option>
						<option>
							<label>Verde</label>
							<value>V</value>
						</option>
						<option>
							<label>Marrón</label>
							<value>M</value>
						</option>
						<option>
							<label>Negro</label>
							<value>N</value>
						</option>
					</options>
				</field>
			</fields>
		</section>
		<section>
			<id />
			<name>Cuarta sección</name>
			<fields>
				<field>
					<id />
					<label>Etiqueta2</label>
					<type>TEXT</type>
					<properties>
						<property>
							<name>font</name>
							<value>Arial</value>
						</property>
					</properties>
				</field>
			</fields>
		</section>
	</sections>
</form>
