=== francabrera/turawet/Resources/Forms/XML/form_def.dtd
<!ELEMENT form  ( id | version | name | author | sections )*>

<!ELEMENT id  ( #PCDATA )>

<!ELEMENT version  ( #PCDATA )>

<!ELEMENT name  ( #PCDATA )>

<!ELEMENT author  ( user )>

<!ELEMENT user  ( #PCDATA )>

<!ELEMENT sections  ( section )*>

<!ELEMENT section  ( id | name | text | date | radio | combo | checkbox | images_gallery | video_gallery | audio_gallery | location )*>

<!ELEMENT text  ( id | label | maxlength | required | value )*>

<!ELEMENT label  ( #PCDATA )>

<!ELEMENT maxlength  ( #PCDATA )>

<!ELEMENT required  ( #PCDATA )>

<!ELEMENT value  ( #PCDATA )>

<!ELEMENT date  ( id | label | required | date_value )*>

<!ELEMENT date_value  ( day | month | year )*>

<!ELEMENT day  ( #PCDATA )>

<!ELEMENT month  ( #PCDATA )>

<!ELEMENT year  ( #PCDATA )>

<!ELEMENT radio  ( id | label | required | options )*>

<!ELEMENT options  ( option )*>

<!ELEMENT option  ( label | value | selected )*>

<!ELEMENT selected  ( #PCDATA )>

<!ELEMENT combo  ( id | label | required | options )*>

<!ELEMENT checkbox  ( id | label | required | options )*>

<!ELEMENT images_gallery  ( id | label | images )*>

<!ELEMENT images  ( image )*>

<!ELEMENT image  ( id | title | binary )*>

<!ELEMENT title  ( #PCDATA )>

<!ELEMENT binary  ( #PCDATA )>

<!ELEMENT video_gallery  ( id | label | videos )*>

<!ELEMENT videos  ( video )>

<!ELEMENT video  ( id | title | binary )*>

<!ELEMENT audio_gallery  ( id | label | audios )*>

<!ELEMENT audios  ( audio )>

<!ELEMENT audio  ( id | title | binary )*>

<!ELEMENT location  ( id | label | required | longitude | latitude )*>

<!ELEMENT longitude  ( #PCDATA )>

<!ELEMENT latitude  ( #PCDATA )>

=== francabrera/turawet/BeeKeeper/trunk/BeeKeeper/form_xml2db_parser/resources/formulario.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE form SYSTEM "form_def.dtd">

<form>
	<id>123</id>
	<version>1</version>
	<name>Formulario de prueba</name>
	<author>
		<user>nicopernas</user>
	</author>
	<sections>
		<section>
			<id>id</id>
			<name>Primera sección</name>
			<text><!-- Elementos tipo texto -->
				<id>id</id>
				<label>Nombre</label>
				<maxlength>100</maxlength>
				<required/>
			</text>
			<date><!-- Elementos tipo fecha -->
				<id>id</id>
				<label>Fecha de nacimiento</label>
				<required/>
				<format>YYYY/MM/DD</format>
			</date>
			<radio><!-- Elementos tipo radio-button -->
				<id>id</id>
				<label>Sexo</label>
				<required>false</required>
				<options>
					<option>
						<label>Masculino</label>
						<id>id</id>
					</option>
					<option>
						<label>Femenino</label>
						<id>id</id>
					</option>
				</options>
			</radio>
			<combo><!-- Elementos tipo combo -->
				<id>id</id>
				<label>Estudios</label>
				<required/>
				<options>
					<option>
						<label>Ingeniería Informática</label>
						<id>id</id>
					</option>
					<option>
						<label>Medicina</label>
						<id>id</id>
					</option>
					<option>
						<label>Farmacia</label>
						<id>id</id>
					</option>
				</options>
			</combo>
			<checkbox><!-- Elementos tipo checkbox -->
				<id>id</id>
				<label>Idiomas</label>
			</checkbox>
			<images_gallery>
				<id>id</id>
				<label>Imágenes</label>
			</images_gallery>
			<video_gallery>
				<id>id</id>
				<label>Vídeos</label>
			</video_gallery>
			<audio_gallery>
				<id>id</id>
				<label>Sonidos</label>
			</audio_gallery>
			<location>
				<id>id</id>
				<label>Localización</label>
			</location>
		</section>
	</sections>
</form>

=== francabrera/turawet/Resources/Forms/XML/instancia.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE form SYSTEM "form_def.dtd">

<form>
	<id>123</id>
	<version>1</version>
	<name>Formulario de prueba</name>
	<author>
		<user>nicopernas</user>
	</author>
	<sections>
		<section>
			<id>id</id>
			<name>Primera sección</name>
			<text><!-- Elementos tipo texto -->
				<id>id</id>
				<label>Nombre</label>
				<maxlength>100</maxlength>
				<required>true</required>
				<value>Nicolás Pernas Maradei</value>
			</text>
			<date><!-- Elementos tipo fecha -->
				<id>id</id>
				<label>Fecha de nacimiento</label>
				<required>true</required>
				<date_value>
					<day>14</day>
					<month>10</month>
					<year>1986</year>
				</date_value>
			</date>
			<radio><!-- Elementos tipo radio-button -->
				<id>id</id>
				<label>Sexo</label>
				<required>false</required>
				<options>
					<option>
						<label>Masculino</label>
						<value>M</value>
                        <selected/>
					</option>
					<option>
						<label>Femenino</label>
						<value>F</value>
					</option>
				</options>
			</radio>
			<combo><!-- Elementos tipo combo -->
				<id>id</id>
				<label>Estudios</label>
				<required>true</required>
				<options>
					<option>
						<label>Ingeniería Informática</label>
						<value>IM</value>
						<selected/>
					</option>
					<option>
						<label>Medicina</label>
						<value>M</value>
					</option>
					<option>
						<label>Farmacia</label>
						<value>F</value>
					</option>
				</options>
			</combo>
			<checkbox><!-- Elementos tipo checkbox -->
				<id>id</id>
				<label>Idiomas</label>
				<required>false</required>

			</checkbox>
			<images_gallery>
				<id>id</id>
				<label>Imágenes</label>
				<images>
					<image>
						<id>id</id>
						<title>IMG_001.jpg</title>
						<binary>12312311323123</binary>
					</image>
					<image>
						<id>id</id>
						<title>IMG_002.jpg</title>
						<binary>12312311323123</binary>
					</image>
				</images>
			</images_gallery>
			<video_gallery>
				<id>id</id>
				<label>Vídeos</label>
				<videos>
					<video>
						<id>id</id>
						<title>2011_01_10.mpg</title>
						<binary>12312311323123</binary>
					</video>
				</videos>
			</video_gallery>
			<audio_gallery>
				<id>id</id>
				<label>Sonidos</label>
				<audios>
					<audio>
						<id>id</id>
						<title>2011_01_10.mp3</title>
						<binary>12312311323123</binary>
					</audio>
				</audios>
			</audio_gallery>
			<location>
				<id>id</id>
				<label>Localización</label>
				<required>false</required>
				<longitude>23.1231</longitude>
				<latitude>34.33234</latitude>
			</location>
		</section>
		<section>
			<id>id</id>
			<name>Segunda sección</name>
			<text><!-- Elementos tipo texto -->
				<id>id</id>
				<label>Comentarios</label>
				<maxlength>200</maxlength>
				<required>false</required>
				<value>Esto es un comentario...</value>
			</text>
		</section>
	</sections>
</form>
